CREATE TABLE items (
	id INTEGER PRIMARY KEY NOT NULL,
	guid TEXT NOT NULL UNIQUE,
	link TEXT NOT NULL,
	title TEXT,
	fetched_at TIMESTAMP NOT NULL,
	feed INTEGER NOT NULL,
	FOREIGN KEY(feed) REFERENCES feeds(id)
);
