CREATE TABLE IF NOT EXISTS feeds (
	id INTEGER PRIMARY KEY NOT NULL,
	kind TEXT NOT NULL,
	url TEXT NOT NULL UNIQUE,
	is_new BOOLEAN NOT NULL DEFAULT TRUE,
	last_fetched_at TIMESTAMP DEFAULT NULL,
	UNIQUE (url) ON CONFLICT IGNORE
);

CREATE TABLE IF NOT EXISTS feed_items (
	id INTEGER PRIMARY KEY NOT NULL,
	feed_id INTEGER NOT NULL,
	title TEXT DEFAULT NULL,
	link TEXT NOT NULL UNIQUE,
	guid TEXT NOT NULL UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	published_at TIMESTAMP DEFAULT NULL,
	FOREIGN KEY (feed_id) REFERENCES feeds(id),
	UNIQUE (guid, link) ON CONFLICT IGNORE
);

CREATE TABLE IF NOT EXISTS webhooks (
	id INTEGER PRIMARY KEY NOT NULL,
	url TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS notifications (
	id INTEGER PRIMARY KEY NOT NULL,
	feed_item_id INTEGER NOT NULL,
	webhook_id INTEGER NOT NULL,
	sent INTEGER NOT NULL,
	sent_at TIMESTAMP,
	FOREIGN KEY (feed_item_id) REFERENCES feed_items(id),
	FOREIGN KEY (webhook_id) REFERENCES webhooks(id),
	UNIQUE (feed_item_id, webhook_id) ON CONFLICT IGNORE
);
